### ISSUE TITLE
Set up for multi-node operation

### ISSUE THREAD

**Issue by abbypribis** [AdaptiveComputationLab/simcov#7]
I encountered this warning in the generated slurm.out file when running with 3 nodes on CARC Xena.

`WARNING: ./install/bin/simcov was compiled with smp backend, which only supports single-node operation. -N option ignored.`
`WARNING: For multi-node operation, please re-compile with UPCXX_NETWORK=<backend>`
`Initial infection coordinates set; will override --infections (1)`
`Initial infection coords specified, setting number of infection points to 1`

And after printing out the config:

`Starting run with 48 processes on 1 node at 11/29/20 21:20:55`
`[39] <main.cpp:641> WARNING: Could not pin process 29783 to core 39`
`[17] <main.cpp:641> WARNING: Could not pin process 29761 to core 17`
`[33] <main.cpp:641> WARNING: Could not pin process 29777 to core 33`
`[21] <main.cpp:641> WARNING: Could not pin process 29765 to core 21`
`[44] <main.cpp:641> WARNING: Could not pin process 29788 to core 44`
`[43] <main.cpp:641> WARNING: Could not pin process 29787 to core 43`
`[18] <main.cpp:641> WARNING: Could not pin process 29762 to core 18`
`[29] <main.cpp:641> WARNING: Could not pin process 29773 to core 29`
`[25] <main.cpp:641> WARNING: Could not pin process 29769 to core 25`
`[24] <main.cpp:641> WARNING: Could not pin process 29768 to core 24`
`[42] <main.cpp:641> WARNING: Could not pin process 29786 to core 42`
`[16] <main.cpp:641> WARNING: Could not pin process 29760 to core 16`
`[22] <main.cpp:641> WARNING: Could not pin process 29766 to core 22`
`[45] <main.cpp:641> WARNING: Could not pin process 29789 to core 45`
`[36] <main.cpp:641> WARNING: Could not pin process 29780 to core 36`
`[34] <main.cpp:641> WARNING: Could not pin process 29778 to core 34`
`[32] <main.cpp:641> WARNING: Could not pin process 29776 to core 32`
`[38] <main.cpp:641> WARNING: Could not pin process 29782 to core 38`
`[23] <main.cpp:641> WARNING: Could not pin process 29767 to core 23`
`[35] <main.cpp:641> WARNING: Could not pin process 29779 to core 35`
`[41] <main.cpp:641> WARNING: Could not pin process 29785 to core 41`
`[26] <main.cpp:641> WARNING: Could not pin process 29770 to core 26`
`[30] <main.cpp:641> WARNING: Could not pin process 29774 to core 30`
`[37] <main.cpp:641> WARNING: Could not pin process 29781 to core 37`
`[40] <main.cpp:641> WARNING: Could not pin process 29784 to core 40`
`[46] <main.cpp:641> WARNING: Could not pin process 29790 to core 46`
`[19] <main.cpp:641> WARNING: Could not pin process 29763 to core 19`
`[20] <main.cpp:641> WARNING: Could not pin process 29764 to core 20`
`[27] <main.cpp:641> WARNING: Could not pin process 29771 to core 27`
`[28] <main.cpp:641> WARNING: Could not pin process 29772 to core 28`
`[31] <main.cpp:641> WARNING: Could not pin process 29775 to core 31`
`[47] <main.cpp:641> WARNING: Could not pin process 29791 to core 47`

This is the only thing I have changed from running with a single node to three nodes:

In the xena_simcov_run.sh script:
`#SBATCH --nodes=3`
INSTEAD OF:
`#SBATCH --nodes=1`

Is this something I need to worry about?

**Comment by KirtusLeyba** [comment]
I'm working through old SIMCoV Issues. Since this issue is stale, I'm going to close it. Please open a new issue if you cannot get SIMCoV running across multiple nodes on any setup and I will attempt to help.
